# Generated by Django 4.2.4 on 2023-09-21 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("allocation", "0006_staff"),
    ]

    operations = [
        migrations.CreateModel(
            name="Rooms",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("roomno", models.CharField(max_length=20)),
            ],
        ),
    ]
